# start with a minimal image
language: c

# use container infrastructure
sudo: false

# share these between builds
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# build on both GHC 7.10.3 and 8.0.1
matrix:
  include:
  - env: GHCVER=7.10.3 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=8.0.1 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.0.1

before_install:
# Download and unpack the stack executable
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
- export PATH=/opt/ghc/$GHCVER/bin:$PATH

script:
- stack --no-terminal --skip-ghc-check test

notifications:
  email: false
